# try:
  # x = 5/10
  # print("inside try")
# except:
  # print("An exception occured ")

# try:
  # x = [2,3,4]
  # print(x[2])
# except IndexError:
    # print("Index error occurre")
# 
# else:
    # print("else") 
# try:
      # print("finally")    
      # raise Exception ("exception object")
# except:
      # print("exception")


